name: build-ubuntu
on: [push, pull_request]
jobs:
  build-ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: sudo apt-get install -y g++ build-essential libssl-dev
      - name: Compile shell
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: maple-shell
          path: maple-shell