name: build-win
on: [push, pull_request]
jobs:
  build-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Remove old OpenSSL
        run:
          rmdir /s /q "C:\Program Files\OpenSSL-Win64" 2>nul
        shell: cmd
      - name: Install tools
        run:
          powershell.exe -Command (new-object System.Net.WebClient).DownloadFile('https://lamkas.dev/public/maple/OpenSSL-Win64.zip','C:\Program Files\OpenSSL-Win64.zip')
        shell: cmd
      - name: Unzip new OpenSSL
        run:
          7z.exe x -y "C:\Program Files\OpenSSL-Win64.zip"
        shell: cmd
      - name: Debug directory
        run:
          dir "C:\Program Files"
        shell: cmd
      - name: Compile shell
        run: make
      - uses: actions/upload-artifact@v2
        with:
          name: maple-shell.exe
          path: maple-shell.exe