name: release-win
on:
  release:
    types: [created]
jobs:
  release-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install tools
        run: choco install make
      - name: Compile shell
        run: make
      - uses: actions/upload-artifact@v2
          with:
            name: maple-shell.exe
            path: maple-shell.exe