name: release-publish
on:
  release:
    types: [created]
jobs:
  release-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Download created artifacts (Linux)
        run: wget -O maple-shell https://lamkas.dev/public/maple/maple-shell
      - name: Download created artifacts (Windows)
        run: wget -O maple-shell.exe https://lamkas.dev/public/maple/maple-shell.exe
      - name: Upload the artifacts (Linux)
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'maple-shell'
      - name: Upload the artifacts (Windows)
        uses: skx/github-action-publish-binaries@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: 'maple-shell.exe'